server:
  port: 8081

spring:
  datasource:
    # using port 5433 to hit the docker container instead of the local service
    url: jdbc:postgresql://localhost:5433/reservasdb
    username: reservas
    password: reservas123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true