version: '3.9'
services:

  postgres:
    image: postgres:15
    container_name: reservas-postgres
    restart: always
    environment:
      POSTGRES_DB: reservasdb
      POSTGRES_USER: reservas
      POSTGRES_PASSWORD: reservas123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: reservas-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@reservas.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  ms-reservas:
    build: ../ms-reservas
    container_name: ms-reservas
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/reservasdb
      SPRING_DATASOURCE_USERNAME: reservas
      SPRING_DATASOURCE_PASSWORD: reservas123
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  gateway:
    build: ../gateway
    container_name: gateway
    restart: always
    environment:
      MS_RESERVAS_URL: http://ms-reservas:8081
      CORS_ORIGINS: http://localhost:5173,http://localhost:5176
    ports:
      - "8080:8080"
    depends_on:
      - ms-reservas

volumes:
  postgres_data: